source "https://rubygems.org"

gem "jekyll", "~> 4.1.1"

group :jekyll_plugins do
  gem "jekyll-stretcher", "~> 0.1"
  gem "jekyll-bookshop", "~> 1.7.1"
  gem "jekyll-svelte-slabs", "~> 0.0.3"
  gem "bookshop-array-structures", "~> 1.4.7"
  gem 'jekyll-browsersync'
end
